# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
<% app_name = Rails.application.class.parent_name.underscore %>

development:
  adapter: postgresql
  database: <%= eventr-toronto %>_development

test:
  adapter: postgresql
  database: <%= eventr-toronto %>_test

production:
  adapter: redis
  database: <%= ENV["REDISCLOUD_URL"] %>
